In [139]:
#dictionary
#help(dictioary) for help
#use import to use dictionary
#If we know we'll be using functions in dictionary frequently we can import it under a shorter alias to save some typing
# You may have seen code that does this with certain popular libraries like Pandas, Numpy, Tensorflow, or Matplotlib(graphing library matplotlib). For example, it's a common convention to import numpy as np and import pandas as pd 
#The as simply renames the imported module. It's equivalent to doing something
#star imports
#import * makes all the module's variables directly accessible to you (without any dotted prefix).
#Bad news: some purists might grumble at you for doing this.
#matplotlib, you'll be coming into contact with objects it defines which represent Subplots, Figures, TickMarks, and Annotations. pandas functions will give you DataFrames and Series.

In [140]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [141]:
# We can see all the names in math using the built-in function dir()
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fma', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [142]:
math.pi

3.141592653589793

In [143]:
#.dot syntax
print('pi has value of {:.5}'.format(math.pi)) #:.5 is significant digits

pi has value of 3.1416


In [144]:
#log function
math.log(32,2)

5.0

In [145]:
#short version
import math as mt
mt.pi

3.141592653589793

In [146]:
#another sort verion
import math
mt=math
mt.pi

3.141592653589793

In [147]:
#importing functions from dictionary
from math import *
print(pi,log(32,2))


3.141592653589793 5.0


In [148]:
#draw back of *
from math import *
from numpy import *
print(pi, log(32, 2))

TypeError: return arrays must be of ArrayType

In [ ]:
#A good compromise is to import only the specific things we'll need from each module:

from math import log, pi
from numpy import asarray

In [ ]:
#numpy
#numpy.random:: numpy.random is a submodule of NumPy that deals with random numbers. It is used to generate random: Numbers , Arrays, Distributions (normal, binomial, etc.), Shuffles, samples


import numpy
print('numpy is ', type(numpy))
print('numpy.random is a', type(numpy.random))
print('numpy.rnadom contain names as...', dir(numpy.random))

numpy is  <class 'module'>
numpy.random is a <class 'module'>
numpy.rnadom contain names as... ['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_bit_generator', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_bit_genera

In [ ]:
print('numpy.random is a {}'.format(type(numpy.random)))

numpy.random is a <class 'module'>


In [ ]:
# #So if we import numpy as above, then calling a function in the random "submodule" will require two dots.
# #import numpy as np

# Random float between 0 and 1
# print(np.random.rand())

# Random integer between 1 and 10
# print(np.random.randint(1, 10))

# Random array of 5 numbers
# print(np.random.rand(5))

# Shuffle an array
# arr = np.array([1, 2, 3, 4, 5])
# np.random.shuffle(arr)
# print(arr)


In [ ]:
rolls=numpy.random.randint(low=1, high=7, size=10)
rolls

array([5, 5, 4, 1, 5, 6, 4, 5, 3, 6], dtype=int32)

In [ ]:
#Three tools for understanding strange objects¶
#1: type() (what is this thing?)
#2: dir() (what can I do with it?)
#3: help() (tell me more)

In [ ]:
# If I want the average roll, the "mean" method looks promising...
rolls.mean()

np.float64(4.4)

In [ ]:
# Or maybe I just want to turn the array into a list, in which case I can use "tolist"
rolls.tolist()

[5, 5, 4, 1, 5, 6, 4, 5, 3, 6]

In [ ]:
# That "ravel" attribute sounds interesting. I'm a big classical music fan.
rolls.ravel

<function ndarray.ravel>

In [ ]:
rolls.ravel()
# help(rolls.ravel)

array([5, 5, 4, 1, 5, 6, 4, 5, 3, 6], dtype=int32)

In [ ]:
help(rolls)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any object that can

In [ ]:
#Operator overloading
[3, 4, 1, 2, 2, 1] + 10


TypeError: can only concatenate list (not "int") to list

In [ ]:
rolls+10

array([15, 15, 14, 11, 15, 16, 14, 15, 13, 16], dtype=int32)

In [ ]:
# At which indices are the dice less than or equal to 3?
rolls<=3

array([False, False, False,  True, False, False, False, False,  True,
       False])

In [ ]:
xlist = [[1,2,3],[2,4,6],]
x=numpy.asarray(xlist)
print('xlist={}\nx=\n{}'.format(xlist,x))

xlist=[[1, 2, 3], [2, 4, 6]]
x=
[[1 2 3]
 [2 4 6]]


In [ ]:
# Get the last element of the second row of our numpy array
x[1,-1]

np.int64(6)

In [ ]:
# Get the last element of the second sublist of our nested list? cannot get:::numpy's ndarray type is specialized for working with multi-dimensional data, so it defines its own logic for indexing, allowing us to index by a tuple to specify the index at each dimension.
xlist[1,-1]


TypeError: list indices must be integers or slices, not tuple

In [ ]:
import tensorflow as tf
# Create two constants, each with value 1
a=tf.constant(1)
b=tf.constant(1)
a + b

# a + b isn't 2, it is (to quote tensorflow's documentation)...

# a symbolic handle to one of the outputs of an Operation. It does not hold the values of that operation's output, but instead provides a means of computing those values in a TensorFlow tf.Session.

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
# It's important just to be aware of the fact that this sort of thing is possible and that libraries will often use operator overloading in non-obvious or magical-seeming ways.

# Understanding how Python's operators work when applied to ints, strings, and lists is no guarantee that you'll be able to immediately understand what they do when applied to a tensorflow Tensor, or a numpy ndarray, or a pandas DataFrame.

In [ ]:
# Get the rows with population over 1m in South America
df[(df['population'] > 10**6) & (df['continent'] == 'South America')]

NameError: name 'df' is not defined

In [ ]:
# This turns out to be directly related to operator overloading.

# When Python programmers want to define how operators behave on their types, they do so by implementing methods with special names beginning and ending with 2 underscores such as __lt__, __setattr__, or __contains__. Generally, names that follow this double-underscore format have a special meaning to Python

print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [ ]:
# import matplotlib.ticker as ticker

# def prettify_graph(graph):
#     """
#     Modify the given graph:
#     - Add a title
#     - Set the y-axis to start at 0
#     - Label the y-axis
#     - Format y-axis ticks as dollar amounts
#     """
#     graph.set_title("Results of 500 Slot Machine Pulls")
#     graph.set_ylim(bottom=0)
#     graph.set_ylabel("Balance")

#     # Format y-axis tick labels as dollar amounts
#     formatter = ticker.FuncFormatter(lambda x, _: '${:,.0f}'.format(x))
#     graph.yaxis.set_major_formatter(formatter)

#     import matplotlib.pyplot as plt

# graph = jimmy_slots.get_graph()
# prettify_graph(graph)
# plt.show()  # This line will display the updated graph

In [ ]:
# Luigi is trying to perform an analysis to determine the best items for winning races on the Mario Kart circuit. He has some data in the form of lists of dictionaries that look like...

# [
#     {'name': 'Peach', 'items': ['green shell', 'banana', 'green shell',], 'finish': 3},
#     {'name': 'Bowser', 'items': ['green shell',], 'finish': 1},
#     # Sometimes the racer's name wasn't recorded
#     {'name': None, 'items': ['mushroom',], 'finish': 2},
#     {'name': 'Toad', 'items': ['green shell', 'mushroom'], 'finish': 1},
# ]
# 'items' is a list of all the power-up items the racer picked up in that race, and 'finish' was their placement in the race (1 for first place, 3 for third, etc.).

[
    {'name': 'Peach', 'items': ['green shell', 'banana', 'green shell',], 'finish': 3},
    {'name': 'Bowser', 'items': ['green shell',], 'finish': 1},
    # Sometimes the racer's name wasn't recorded
    {'name': None, 'items': ['mushroom',], 'finish': 2},
    {'name': 'Toad', 'items': ['green shell', 'mushroom'], 'finish': 1},
]

def best_items(racers):
    """Given a list of racer dictionaries, return a dictionary mapping items to the number
    of times those items were picked up by racers who finished in first place.
    """
    winner_item_counts = {}
    for i in range(len(racers)):
        # The i'th racer dictionary
        racer = racers[i]
        # We're only interested in racers who finished in first
        if racer['finish'] == 1:
            for i in racer['items']:
                # Add one to the count for this item (adding it to the dict if necessary)
                if i not in winner_item_counts:
                    winner_item_counts[i] = 0
                winner_item_counts[i] += 1

        # Data quality issues :/ Print a warning about racers with no name set. We'll take care of it later.
        if racer['name'] is None:
            print("WARNING: Encountered racer with unknown name on iteration {}/{} (racer = {})".format(
                i+1, len(racers), racer['name'])
                 )
    return winner_item_counts


In [ ]:
sample = [
    {'name': 'Peach', 'items': ['green shell', 'banana', 'green shell',], 'finish': 3},
    {'name': 'Bowser', 'items': ['green shell',], 'finish': 1},
    {'name': None, 'items': ['mushroom',], 'finish': 2},
    {'name': 'Toad', 'items': ['green shell', 'mushroom'], 'finish': 1},
]
best_items(sample)


{'green shell': 2, 'mushroom': 1}

In [ ]:
# # Import luigi's full dataset of race data

# # Fix me!
# def best_items(racers):
#     winner_item_counts = {}
#     for i in range(len(racers)):
#         # The i'th racer dictionary
#         racer = racers[i]
#         # We're only interested in racers who finished in first
#         if racer['finish'] == 1:
#             for item in racer['items']:
#                 # Add one to the count for this item (adding it to the dict if necessary)
#                 if i not in winner_item_counts:
#                     winner_item_counts[i] = 0
#                 winner_item_counts[i] += 1

#         # Data quality issues :/ Print a warning about racers with no name set. We'll take care of it later.
#         if racer['name'] is None:
#             print("WARNING: Encountered racer with unknown name on iteration {}/{} (racer = {})".format(
#                 i+1, len(racers), racer['name'])
#                  )
#     return winner_item_counts

# # Try analyzing the imported full dataset
# best_items()


In [150]:
# Suppose we wanted to create a new type to represent hands in blackjack. One thing we might want to do with this type is overload the comparison operators like > and <= so that we could use them to check whether one hand beats another. e.g. it'd be cool if we could do this:

# >>> hand1 = BlackjackHand(['K', 'A'])
# >>> hand2 = BlackjackHand(['7', '10', 'A'])
# >>> hand1 > hand2
# True
# Well, we're not going to do all that in this question (defining custom classes is a bit beyond the scope of these lessons), but the code we're asking you to write in the function below is very similar to what we'd have to write if we were defining our own BlackjackHand class. (We'd put it in the __gt__ magic method to define our custom behaviour for >.)

# Fill in the body of the blackjack_hand_greater_than function according to the docstring.


def hand_total(hand):
    """
    Return True if hand_1 beats hand_2, and False otherwise.
    
    In order for hand_1 to beat hand_2 the following must be true:
    - The total of hand_1 must not exceed 21
    - The total of hand_1 must exceed the total of hand_2 OR hand_2's total must exceed 21
    
    Hands are represented as a list of cards. Each card is represented by a string.
    
    When adding up a hand's total, cards with numbers count for that many points. Face
    cards ('J', 'Q', and 'K') are worth 10 points. 'A' can count for 1 or 11.
    
    When determining a hand's total, you should try to count aces in the way that 
    maximizes the hand's total without going over 21. e.g. the total of ['A', 'A', '9'] is 21,
    the total of ['A', 'A', '9', '3'] is 14.
    
    Examples:
    >>> blackjack_hand_greater_than(['K'], ['3', '4'])
    True
    >>> blackjack_hand_greater_than(['K'], ['10'])
    False
    >>> blackjack_hand_greater_than(['K', 'K', '2'], ['3'])
    False 
    >>> Helper function to calculate the total points of a blackjack hand.
    """
    total = 0
    # Count the number of aces and deal with how to apply them at the end.
    aces = 0
    for card in hand:
        if card in ['J', 'Q', 'K']:
            total += 10
        elif card == 'A':
            aces += 1
        else:
            # Convert number cards (e.g. '7') to ints
            total += int(card)
    # At this point, total is the sum of this hand's cards *not counting aces*.

    # Add aces, counting them as 1 for now. This is the smallest total we can make from this hand
    total += aces
    # "Upgrade" aces from 1 to 11 as long as it helps us get closer to 21
    # without busting
    while total + 10 <= 21 and aces > 0:
        # Upgrade an ace from 1 to 11
        total += 10
        aces -= 1
    return total

def blackjack_hand_greater_than(hand_1, hand_2):
    total_1 = hand_total(hand_1)
    total_2 = hand_total(hand_2)
    return total_1 <= 21 and (total_1 > total_2 or total_2 > 21)